config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :diaries
  resources :user_info_details
  resources :user_infos
  resources :users
  resources :angles
  resources :tulpa_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "test", to: "apis#test"
  # Defines the root path route ("/")

  post "tulpa-detail", to: "tulpas#detail"
  post "tulpa-main", to: "tulpas#main"
  
  root "tulpas#dummy"
end

app/models/angle.rb
class Angle < ApplicationRecord

    def set_categories category_list
        unselected_category_list = []
        AngleCategory.all.each do |ac|
            unless category_list.include?(ac.id.to_s)
                unselected_category_list.push(ac.id.to_s)
            end
        end
        
        category_list.each do |category|
            aac = AngleAngleCategory.find_by(category_id: category, angle_id: self.id)
            if aac.blank?
                aac = AngleAngleCategory.new
                aac.category_id = category.to_i
                aac.angle_id = self.id
                aac.is_enabled = true
                aac.save
            elsif aac.is_enabled = false
                aac.is_enabled = true
                aac.save
            end
        end
        
        unselected_category_list.each do |category|
            aac = AngleAngleCategory.find_by(category_id: category, angle_id: self.id)
            unless aac.blank?
                aas.is_enabled = false
                aac.save
            end
        end
    end

end

app/controllers/angles_controller.rb
class AnglesController < ApplicationController
  before_action :set_angle, only: %i[ show edit update destroy ]

  # GET /angles or /angles.json
  def index
    @angles = Angle.all
  end

  # GET /angles/1 or /angles/1.json
  def show
  end

  # GET /angles/new
  def new
    @angle = Angle.new
    categories = AngleCategory.all.order(:id)
    @categories = []
    categories.each do |category|
      @categories.push({id: category.id, name: category.name, selected: false})
    end
  end

  # GET /angles/1/edit
  def edit
    categories = AngleCategory.all.order(:id)
    @categories = []
    categories.each do |category|
      aac = AngleAngleCategory.find_by(category_id: category.id, angle_id: @angle.id, is_enabled: true)
      if aac.blank?
        @categories.push({id: category.id, name: category.name, selected: false})
      else
        @categories.push({id: category.id, name: category.name, selected: true})
      end
    end
  end

  # POST /angles or /angles.json
  def create
    logger.debug params
    @angle = Angle.new(angle_params)

    respond_to do |format|
      if @angle.save
        @angle.set_categories params[:categories]
        format.html { redirect_to angle_url(@angle), notice: "Angle was successfully created." }
        format.json { render :show, status: :created, location: @angle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @angle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /angles/1 or /angles/1.json
  def update
    @angle.set_categories params[:categories]
    respond_to do |format|
      if @angle.update(angle_params)
        format.html { redirect_to angle_url(@angle), notice: "Angle was successfully updated." }
        format.json { render :show, status: :ok, location: @angle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @angle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /angles/1 or /angles/1.json
  def destroy
    @angle.destroy

    respond_to do |format|
      format.html { redirect_to angles_url, notice: "Angle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_angle
      @angle = Angle.find(params[:id])
    end

    def set_categories
    end

    # Only allow a list of trusted parameters through.
    def angle_params
      params.require(:angle).permit(:name)
    end
end

app/helpers/angles_helper.rb
module AnglesHelper
end

app/views/angles/_angle.html.erb
<div id="<%= dom_id angle %>">
  <p>
    <strong>Name:</strong>
    <%= angle.name %>
  </p>

</div>

app/views/angles/_form.html.erb
<%= form_with(model: angle) do |form| %>
  <% if angle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(angle.errors.count, "error") %> prohibited this angle from being saved:</h2>

      <ul>
        <% angle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% @categories.each do |c| %>
      <% if c[:selected] %>
        <input type="checkbox" name="categories[]" value="<%= c[:id] %>" checked="checked"><%= c[:name] %>
      <% else %>
        <input type="checkbox" name="categories[]" value="<%= c[:id] %>"><%= c[:name] %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/angles/edit.html.erb
<h1>Editing angle</h1>

<%= render "form", angle: @angle %>

<br>

<div>
  <%= link_to "Show this angle", @angle %> |
  <%= link_to "Back to angles", angles_path %>
</div>

app/views/angles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Angles</h1>

<div id="angles">
  <% @angles.each do |angle| %>
    <%= render angle %>
    <p>
      <%= link_to "Show this angle", angle %>
    </p>
  <% end %>
</div>

<%= link_to "New angle", new_angle_path %>

app/views/angles/new.html.erb
<h1>New angle</h1>

<%= render "form", angle: @angle %>

<br>

<div>
  <%= link_to "Back to angles", angles_path %>
</div>

app/views/angles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @angle %>

<div>
  <%= link_to "Edit this angle", edit_angle_path(@angle) %> |
  <%= link_to "Back to angles", angles_path %>

  <%= button_to "Destroy this angle", @angle, method: :delete %>
</div>