config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :diaries
  resources :user_info_details
  resources :user_infos
  resources :users
  resources :angles
  resources :tulpa_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "test", to: "apis#test"
  # Defines the root path route ("/")

  post "tulpa-detail", to: "tulpas#detail"
  post "tulpa-main", to: "tulpas#main"
  
  root "tulpas#dummy"
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]
  before_action :confirm_fb_token

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)
    respond_to do |format|
      if @diary.confirm_and_save(diary_params, @user)
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.confirm_and_update(diary_params, @user)
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:text, :user_info_id)
    end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_diary.html.erb
<div id="<%= dom_id diary %>">
  <p>
    <strong>User info:</strong>
    <%= diary.user_info_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= diary.text %>
  </p>

</div>

app/views/diaries/_form.html.erb
<%= form_with(model: diary) do |form| %>
  <% if diary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_info_id %>
  </div>

  <div>
    <%= form.label :出来事, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Show this diary", @diary %> |
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Diaries</h1>

<div id="diaries">
  <% @diaries.each do |diary| %>
    <%= render diary %>
    <p>
      <%= link_to "Show this diary", diary %>
    </p>
  <% end %>
</div>

<%= link_to "New diary", new_diary_path %>

app/views/diaries/new.html.erb
<h1>New diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @diary %>

<div>
  <%= link_to "Edit this diary", edit_diary_path(@diary) %> |
  <%= link_to "Back to diaries", diaries_path %>

  <%= button_to "Destroy this diary", @diary, method: :delete %>
</div>