config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :diaries
  resources :user_info_details
  resources :user_infos
  resources :users
  resources :angles
  resources :tulpa_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "test", to: "apis#test"
  # Defines the root path route ("/")

  post "tulpa-detail", to: "tulpas#detail"
  post "tulpa-main", to: "tulpas#main"
  
  root "tulpas#dummy"
end

app/models/user_info_detail.rb
class UserInfoDetail < ApplicationRecord
    validates :category_id, numericality: {greater_than: 0}

    def out
        return {id: self.id, text: self.text}
    end
end

app/controllers/user_info_details_controller.rb
class UserInfoDetailsController < ApplicationController
  before_action :set_user_info_detail, only: %i[ show edit update destroy ]
  before_action :confirm_fb_token

  # GET /user_info_details or /user_info_details.json
  def index
    @user_info_details = UserInfoDetail.all
  end

  # GET /user_info_details/1 or /user_info_details/1.json
  def show
  end

  # GET /user_info_details/new
  def new
    @user_info_detail = UserInfoDetail.new
  end

  # GET /user_info_details/1/edit
  def edit
  end

  # POST /user_info_details or /user_info_details.json
  def create
    @user_info_detail = UserInfoDetail.new(user_info_detail_params)

    respond_to do |format|
      if @user_info_detail.confirm_and_save( user_info_detail_params, @user )
        format.html { redirect_to user_info_detail_url(@user_info_detail), notice: "User info detail was successfully created." }
        format.json { render :show, status: :created, location: @user_info_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_info_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_info_details/1 or /user_info_details/1.json
  def update
    respond_to do |format|
      if @user_info_detail.confirm_and_update(user_info_detail_params, @user)
        format.html { redirect_to user_info_detail_url(@user_info_detail), notice: "User info detail was successfully updated." }
        format.json { render :show, status: :ok, location: @user_info_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_info_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_info_details/1 or /user_info_details/1.json
  def destroy
    @user_info_detail.destroy

    respond_to do |format|
      format.html { redirect_to user_info_details_url, notice: "User info detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info_detail
      @user_info_detail = UserInfoDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_info_detail_params
      params.require(:user_info_detail).permit(:text, :category_id, :user_info_id)
    end
end

app/helpers/user_info_details_helper.rb
module UserInfoDetailsHelper
end

app/views/user_info_details/_form.html.erb
<%= form_with(model: user_info_detail) do |form| %>
  <% if user_info_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_info_detail.errors.count, "error") %> prohibited this user_info_detail from being saved:</h2>

      <ul>
        <% user_info_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :種類分け, style: "display: block" %>
    <select name="user_info_detail[category_id]" id="user_info_detail_category_id">
    <option value="0">選択してください</option>
      <% UserInfoCategory.all.each do |category| %>
        <option value="<%= category.id %>"><%= category.type_name %></option>
      <% end %>
    </select>
  </div>

  <div>
    <%= form.label :特徴, style: "display: block" %>
    <%= form.text_field :text %>
  </div>
  <%= form.hidden_field :user_info_id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_info_details/_user_info_detail.html.erb
<div id="<%= dom_id user_info_detail %>">
  <p>
    <strong>Text:</strong>
    <%= user_info_detail.text %>
  </p>

  <p>
    <strong>User info:</strong>
    <%= user_info_detail.user_info_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= user_info_detail.category_id %>
  </p>

</div>

app/views/user_info_details/edit.html.erb
<h1>Editing user info detail</h1>

<%= render "form", user_info_detail: @user_info_detail %>

<br>

<div>
  <%= link_to "Show this user info detail", @user_info_detail %> |
  <%= link_to "Back to user info details", user_info_details_path %>
</div>

app/views/user_info_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User info details</h1>

<div id="user_info_details">
  <% @user_info_details.each do |user_info_detail| %>
    <%= render user_info_detail %>
    <p>
      <%= link_to "Show this user info detail", user_info_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New user info detail", new_user_info_detail_path %>

app/views/user_info_details/new.html.erb
<h1>New user info detail</h1>

<%= render "form", user_info_detail: @user_info_detail %>

<br>

<div>
  <%= link_to "Back to user info details", user_info_details_path %>
</div>

app/views/user_info_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_info_detail %>

<div>
  <%= link_to "Edit this user info detail", edit_user_info_detail_path(@user_info_detail) %> |
  <%= link_to "Back to user info details", user_info_details_path %>

  <%= button_to "Destroy this user info detail", @user_info_detail, method: :delete %>
</div>